version: '2.4'

services:

  chmfc:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: chmfc
    environment:
      CHMFC_CH_HOST: clickhouse
      CHMFC_CH_LOGIN: test
      CHMFC_CH_PASSWORD: test
      CHMFC_CH_DATABASE: default
      CHMFC_MIG_PATH: /migrations
      CHMFC_MIG_TABLE: default.migrations
    volumes:
      - ../test-migrations:/migrations
    depends_on:
      clickhouse:
        condition: service_healthy
      clickhouse1:
        condition: service_healthy

  clickhouse:
    image: yandex/clickhouse-server:21.8.5.7
    container_name: test_clickhouse
    volumes:
      - ./clickhouse/macros.xml:/etc/clickhouse-server/conf.d/macros.xml
      - ./clickhouse/zookeeper.xml:/etc/clickhouse-server/conf.d/zookeeper.xml
      - ./clickhouse/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
    environment:
      CLICKHOUSE_DB: test
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: test
      REPLICA_NAME: clickhouse
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      zookeeper:
        condition: service_started

  clickhouse1:
    image: yandex/clickhouse-server:21.8.5.7
    container_name: test_clickhouse1
    volumes:
      - ./clickhouse/macros.xml:/etc/clickhouse-server/conf.d/macros.xml
      - ./clickhouse/zookeeper.xml:/etc/clickhouse-server/conf.d/zookeeper.xml
      - ./clickhouse/remote_servers.xml:/etc/clickhouse-server/config.d/remote_servers.xml
    environment:
      CLICKHOUSE_DB: test
      CLICKHOUSE_USER: test
      CLICKHOUSE_PASSWORD: test
      REPLICA_NAME: clickhouse1
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      zookeeper:
        condition: service_started

  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    hostname: zookeeper

networks:
  default:
    name: test
